services:
  - type: web
    name: rickortys8
    env: node
    buildCommand: npm install && npm run build:server && npm run build:client
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RENDER_URL
        sync: false