services:
  - type: web
    name: rickortys8
    runtime: node
    buildCommand: npm install && npm run build:server && npm run build:client
    startCommand: node src/dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RENDER_URL
        sync: false